=== dhh1128/did-method-webs/acdc/schema/ns-aid-auth-schema.json
{"$id": "EPi_tVS3zDN4wo-T3NQb5pUtdeup98yoJ_hrNReD86xO", "$schema": "http://json-schema.org/draft-07/schema#", "title": "Identifier Authorization attestation", "description": "An Authorization attestation by an AID controller, to acknowledge and authorize a namespaced identifier whose AID post-fix matches the controller AID.", "type": "object", "credentialType": "IdentifierAuthorizationAttestation", "version": "1.0.0", "properties": {"v": {"description": "Version", "type": "string"}, "d": {"description": "Attestation SAID", "type": "string"}, "u": {"description": "One time use nonce", "type": "string"}, "i": {"description": "Controller AID", "type": "string"}, "ri": {"description": "Attestation status registry", "type": "string"}, "s": {"description": "schema section", "oneOf": [{"description": "schema section SAID", "type": "string"}, {"description": "schema detail", "type": "object"}]}, "a": {"oneOf": [{"description": "Attributes block SAID", "type": "string"}, {"$id": "EDrKz5DhueGqlJYOYktdPDX0wJ9f-dVSiuwcJWCDAavF", "description": "Attributes block", "type": "object", "properties": {"d": {"description": "Attributes block SAID", "type": "string"}, "u": {"description": "One time use nonce", "type": "string"}, "dt": {"description": "Authorization date time", "type": "string", "format": "date-time"}, "ids": {"description": "Set of namespaced/controlled AID identifiers that the AID controller authorizes", "type": "array", "items": {"type": "string"}}}, "additionalProperties": false, "required": ["d", "dt", "ids"]}]}, "r": {"oneOf": [{"description": "Rules block SAID", "type": "string"}, {"$id": "ECLt7Scjsf1inplLDNLoOpcPqq-nX8h5l56t1lY4HuyN", "description": "Rules block", "type": "object", "properties": {"d": {"description": "Rules block SAID", "type": "string"}, "usageDisclaimer": {"description": "Usage Disclaimer", "type": "object", "properties": {"l": {"description": "Clarification regarding control", "type": "string", "const": "This attestation only asserts an authorization from the controller of the AID, that the AID controlled namespaced identifier is known and authorized by the controller. It does not assert that the controller of this AID has control of the infrastructure or other systems related to the hosting of the namespaced AID identifier. For instance, a did:webs DID is controlled by an AID but the domain name hosting that DID is not necessarily under the control of the AID controller."}}}, "issuanceDisclaimer": {"description": "Issuance Disclaimer", "type": "object", "properties": {"l": {"description": "Accuracy of information", "type": "string", "const": "All information in a valid and non-revoked Identifier Authorization assertion is accurate as of the date specified."}}}, "privacyDisclaimer": {"description": "Privacy Disclaimer", "type": "object", "properties": {"l": {"description": "Privacy-preservation expectations", "type": "string", "const": "If the assertioin is blinded with the UUID field the assertion should be used in a non-correlating and privacy-preserving manner."}}}}, "additionalProperties": false, "required": ["d", "usageDisclaimer", "issuanceDisclaimer", "privacyDisclaimer"]}]}}, "additionalProperties": false, "required": ["v", "d", "i", "ri", "s", "a", "r"]}

=== dhh1128/did-method-webs/acdc/schema/examples/ns-aid-auth.json
{
    "v": "ACDC10JSON000644_",
    "d": "",
    "i": "EPmX8LcHyBCoFZhvrGsnlZcL6m3wad5x97XsEefxDVHl",
    "ri": "",
    "s": "EPi_tVS3zDN4wo-T3NQb5pUtdeup98yoJ_hrNReD86xO",
    "a": {
        "d": "EJe8AdTwaPfIh1NGq2iAN7DRUVLRie4ktbovbSwR7yBG",
        "dt": "2023-11-13T17:41:37.710691+00:00",
        "ids": [
            "did:webs:example.org:EPmX8LcHyBCoFZhvrGsnlZcL6m3wad5x97XsEefxDVHl"
        ]
    },
    "r": {
        "d": "EGew6U0wBSfe9kISRrMrBHmKrcaIncMLhl87AboKMbv_",
        "usageDisclaimer": {
            "l": "This attestation only asserts an authorization from the controller of the AID, that the AID controlled namespaced identifier is known and authorized by the controller. It does not assert that the controller of this AID has control of the infrastructure or other systems related to the hosting of the namespaced AID identifier. For instance, a did:webs DID is controlled by an AID but the domain name hosting that DID is not necessarily under the control of the AID controller."
        },
        "issuanceDisclaimer": {
            "l": "All information in a valid and non-revoked Identifier Authorization assertion is accurate as of the date specified."
        },
        "privacyDisclaimer": {
            "l": "If the assertioin is blinded with the UUID field the assertion should be used in a non-correlating and privacy-preserving manner."
        }
    }
}
